name = "QuasiNewtonMethods"
uuid = "64452400-c6f4-4a1d-a4f6-ad403655768a"
authors = ["Chris Elrod <elrodc@gmail.com>"]
version = "0.1.3"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
StrideArrays = "d1fa6d79-ef01-42a6-86c9-f7c551f8593b"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[compat]
LoopVectorization = "0.12.85"
StrideArrays = "0.1.2"
VectorizationBase = "0.21"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
