name = "QuasiNewtonMethods"
uuid = "64452400-c6f4-4a1d-a4f6-ad403655768a"
authors = ["Chris Elrod <elrodc@gmail.com>"]
version = "0.1.4"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
StrideArraysCore = "7792a7ef-975c-4747-a70f-980b88e8d1da"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[compat]
LoopVectorization = "0.12.85"
StrideArraysCore = "0.4"
VectorizationBase = "0.21"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
